config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  get '/playlist', to: 'playlists#show_mine'
  put '/playlist/refresh', to: 'playlists#refresh'

  get '/preferences', to: 'preferences#edit'
  put '/preferences', to: 'preferences#update'
  delete '/users/:id', to: 'preferences#delete_user', as: 'user'

  get '/start', to: 'start_page#start'
  put '/start', to: 'start_page#save'

  get '/charts', to: 'mood_ratings#index_mine'
  post '/mood-ratings', to: 'mood_ratings#create'
  get '/admin', to: 'admin#index'

end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_preferences

  def edit
  end

  def update
    location = Location.new_from_city(preference_params[:city])
    
    if location.save
      current_user.location = location
      current_user.save
      flash[:notice] = 'Your preferences were updated successfully.'
      redirect_to action: :edit
    else
      flash.now[:error] = 'Could not update your preferences.'
      render :edit
    end
  end

  def delete_user
    if params[:id] == current_user.id.to_s
      if current_user.destroy
        redirect_to root_path, notice: "Your Spotify account has been disconnected and all data deleted."
      else
        redirect_to preferences_path, flash: { error: "Could not delete your account." }
      end
    else
      redirect_to preferences_path, flash: { error: "Could not delete that account." }
    end
  end

  private

  def set_preferences
    location = current_user.location

    @city = location ? location.name : nil;
  end

  def preference_params
    params.permit(:city)
  end
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/views/preferences/edit.html.erb
<%= flash_messages %>

<div class="preferences-view">

  <h1>Preferences</h1>
  <p><%= link_to "← Back to playlist", playlist_path %></p>

  <%= form_with method: "put" do %>
    <div class="form-field">
      <%= label_tag :city, "City/town:" %>
      <%= text_field_tag :city, @city, placeholder: "E.g. Berlin, DE" %>
      <p class="form-field_help">Used to retrieve weather data for your location.</p>
    </div>
    <%= submit_tag "Save changes", class: "button" %>
  <% end %>

  <section class="preferences-view_delete">
    <h2>Delete account</h2>
    <p>If you'd like to disconnect your Spotify account and <strong>delete all data</strong> associated with the account including <strong>your playlist</strong> and <strong>mood ratings</strong>, click the button below.</p>
    <%= button_to "Disconnect and delete data", user_path(current_user), method: :delete, class: "button -warning", data: { confirm: "Are you sure you wish to delete your account? This action cannot be reversed." } %>
  </section>

</div>