config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  get '/playlist', to: 'playlists#show_mine'
  put '/playlist/refresh', to: 'playlists#refresh'

  get '/preferences', to: 'preferences#edit'
  put '/preferences', to: 'preferences#update'
  delete '/users/:id', to: 'preferences#delete_user', as: 'user'

  get '/start', to: 'start_page#start'
  put '/start', to: 'start_page#save'

  get '/charts', to: 'mood_ratings#index_mine'
  post '/mood-ratings', to: 'mood_ratings#create'
  get '/admin', to: 'admin#index'

end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tracks

  before_destroy :clear

  ##
  # Returns the number of tracks in the playlist
  #
  # @return [Integer]
  def size
    tracks.size
  end

  ##
  # Calculates the average valence of the tracks in the playlist
  #
  # @return [Float]
  def avg_valence
    total_valence = self.tracks.reduce(0) { |sum, track| sum + track.valence }
    total_valence / self.tracks.length
  end

  ##
  # Finds the track with the largest valence value in the playlist and returns the valence for that track
  #
  # @return [Float]
  def max_valence
    track = tracks.max { |a, b| a.valence <=> b.valence }
    track.valence
  end

  ##
  # Finds the track with the smallest valence value in the playlist and returns the valence for that track
  #
  # @return [Float]
  def min_valence
    track = tracks.min { |a, b| a.valence <=> b.valence }
    track.valence
  end

  ##
  # Returns a hash of all the valence values in the playlist (rounded to one decimal place) with a count of the number of tracks with each valence value
  #
  # @return [Hash]
  def valence_distribution
    counts = Hash.new(0)
    tracks.each { |track| counts[track.valence.round(1)] += 1 }
    counts
  end

  ##
  # Adds songs to the playlist based on the user's listening history and the +target_valence+. The average valence of the songs added to the playlist should be roughly equal to +target_valence+.
  #
  # @param [Float] target_valence The target average valence of the added songs
  # @param [Integer] num_songs The number of songs to add to the playlist
  #
  # @return [Integer] The number of songs added to the playlist
  def populate(target_valence, num_songs)
    candidate_tracks = self.user.recommended_tracks(target_valence)
    track_weights = {}
    weights_sum = 0

    # Assign each track a weight, add it to the track_weights hash and calculate the sum of all the weights
    candidate_tracks.each do |track|
      # Calculate the weight of each track by finding the percentage difference between the target_valence and the track's valence
      diff = target_valence - track.valence
      percent_diff = diff.abs / ((target_valence + track.valence) / 2)
      percent_diff = 1 if percent_diff > 1

      # Tracks with a valence close to the target valence will have a weight near 1 and tracks with valence far away will have a weight near 0
      track_weights[track] = 1 - percent_diff
      weights_sum += track_weights[track]
    end

    # Select songs from the pool at semi-random and add them to the playlist
    num_songs.times do
      track = select_random_track(track_weights, weights_sum)
      # The following select method call is workaround for strange behaviour when calling track_weights[track] or track_weights.fetch(track) (both return nil even when track exists in track_weights)
      weights_sum -= track_weights.select{|t, w| t.id == track.id }.values[0]

      self.tracks << track
      track_weights.delete_if {|t, w| t.id == track.id }
    end
  end

  ##
  # Clears playlist and repopulates it with songs based on the user's listening history and the +target_valence+. The average valence of the songs in the playlist should be roughly equal to +target_valence+.
  #
  # @param [Float] target_valence The target average valence of the songs in playlist
  # @param [Integer] num_songs The number of songs to add to the playlist
  #
  # @return [Integer] The number of songs added to the playlist
  def repopulate(target_valence, num_songs)
    clear
    populate(target_valence, num_songs)
  end

  ##
  # Removes each track from the playlist, deleting it if it is no longer part of any playlists
  #
  # @return [Playlist]
  def clear
    tracks.each do |track|
      tracks.delete(track)
      track.destroy if track.playlists.size == 0
    end
  end

  ##
  # Clear all playlists where the user has been inactive for 30 days or more.
  def self.clear_stale
    User.where("updated_at < ?", 30.days.ago).each do |user|
      user.playlist.clear
    end
  end

  private

  ##
  # Selects a track according to a weighted random number algorithm, which is more likely to return tracks with a higher weight
  #
  # Adapted from https://www.rubyguides.com/2016/05/weighted-random-numbers/
  #
  # @param [Hash] track_weights Tracks with associated weights
  # @param [Numeric] weights_sum The sum of all weights
  #
  # @return [Track]
  def select_random_track(track_weights, weights_sum)
    random_num = rand(weights_sum) # Get a random number >= 0 and < weights_sum
    track_weights.each do |track, weight|
      return track if random_num <= weight
      random_num -= weight
    end
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :authenticate_user!
  before_action :show_start_page

  def show_mine
    @playlist = current_user.playlist
    @location = current_user.location

    # Ensure user token is valid to allow playback using the Spotify Web Playback SDK
    current_user.refresh_token
    # Update weather data for view and for target valence calculation
    @location.update_weather_data if @location

    @playlist.populate(current_user.target_valence, 30) if @playlist.size == 0
    
    render :show_mine
  end

  def refresh
    # Update weather data for target valence calculation
    current_user.location.update_weather_data if current_user.location

    current_user.playlist.repopulate(current_user.target_valence, 30)
    redirect_to playlist_path
  end

  private

  def show_start_page
    redirect_to start_path if current_user.privacy_consent_needed? ||
                              !current_user.location ||
                              current_user.time_since_last_mood_rating > 12.hours
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  def weather_icon(code, alt)
    suffix = 
      case code
        when "01d"
          "sunny"
        when "01n"
          "clear"
        when "02d"
          "mostly-sunny"
        when "02n"
          "mostly-clear"
        when "03d", "03n"
          "partly-cloudy"
        when "04d", "04n"
          "mostly-cloudy"
        when "09d", "09n", "10d", "10n"
          "rain"
        when "11d", "11n"
          "thunder"
        when "13d", "13n"
          "snow"
        when "50d", "50n"
          "fog"
      end

    url = "/assets/weather_#{suffix}.svg"
    image_tag(url, alt: alt)
  end
end

app/views/playlists/_control_bar.html.erb
<div class="control-bar" data-js-control-bar>
  <div class="control-bar_inner">
    <img class="control-bar_image" data-js-image src="" alt="">
    <div class="control-bar_track-info">
      <div class="control-bar_title" data-js-title></div>
      <div data-js-album-info></div>
    </div>
    <div class="control-bar_controls">
      <button class="control-bar_prev" data-js-prev>Prev</button>
      <button class="control-bar_play" data-js-play>Play</button>
      <button class="control-bar_pause" data-js-pause>Pause</button>
      <button class="control-bar_next" data-js-next>Next</button>
    </div>
    <input class="control-bar_scrubber" type="range" min="1" max="1000" value="0" data-js-scrubber>
  </div>
</div>

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>
      <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-md-4">
    <%= f.label :rating %><br>
    <%= f.text_field :rating, class: "form-control" %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit 'Create', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/playlists/_toggle.html.erb
<div class="toggle">
  <input type="radio" name="view" id="playlist" value="playlist" checked data-js-pane-option>
  <input type="radio" name="view" id="charts" value="charts" data-js-pane-option>
  <label for="playlist">Playlist</label>
  <label for="charts">Charts</label>
</div>

app/views/playlists/_track_listing.html.erb
<table class="track-listing">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Artist</th>
      <th>Album</th> 
    </tr>
  </thead>
  <tbody>
    <% @playlist.tracks.each do |track| %>
      <tr data-js-spotify-track="<%= track.spotify_id %>">
        <td><%= image_tag(track.image, size: 40, alt: "") %></td>
        <td><%= track.name %></td>
        <td><%= track.artist.truncate(30) %></td>
        <td><%= track.album.truncate(30) %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

app/views/playlists/_weather.html.erb
<% if location %>
  <div class="weather" data-js-weather="<%= location.id %>">
    <div class="weather_info">
      <div><%= location.name %></div>
      <div class="weather_condition"><%= location.condition_description.capitalize %></div>
      <div><%= location.feels_like.round %>°C</div>
    </div>
    <div class="weather_icon">
      <%= weather_icon(location.condition_icon, location.condition_description) %>
    </div>
  </div>
<% else %>
  <p>No location is configured. Please provide a location in <%= link_to "Preferences", preferences_path %>.</p>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Show', @playlist, class: "btn btn-warning" %> |
<%= link_to 'Back', playlists_path, class: "btn btn-default" %>

app/views/playlists/index.html.erb
<%= flash_messages %>

<h2>Playlist List</h2>
<div class="playlist-block">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="col-md-2">Name</th>
        <th class="col-md-2">Rating</th>
        <th class="col-md-2">Creator</th>
        <th class="col-md-4">Options</th>
      </tr>
    </thead>

    <tbody>
      <% @playlists.each do |playlist| %>
        <tr>
          <td class="col-md-2"><%= playlist.name %></td>
          <td class="col-md-2"><%= playlist.rating %></td>
          <td class="col-md-2"><%= playlist.user.try(:email) %></td>
          <td class="col-md-4">
            <%= link_to 'Show', playlist_path(playlist), class: "btn btn-info" %>
            <%= link_to 'Edit', edit_playlist_path(playlist), class: "btn  btn-warning" %>
            <%= link_to 'Destroy', playlist_path(playlist), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Product', new_playlist_path, class: "btn btn-primary" %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Back', playlists_path, class: "btn btn-default" %>

app/views/playlists/show.html.erb
<%= flash_messages %>

<h2>Weather</h2>

<%= render 'weather', location: @location %>

<h2>My playlist</h2>

<%= button_to "Refresh playlist", playlist_refresh_path, :method => :put %>

<div data-js-player="<%= @current_user.credentials["token"] %>">
  <script src="https://sdk.scdn.co/spotify-player.js"></script>
  <div data-js-error></div>
  <table>
    <tbody>
      <% @playlist.tracks.each do |track| %>
        <tr data-js-spotify-track="<%= track.spotify_id %>">
          <td><%= image_tag(track.image, size: 45) %></td>
          <td><%= track.name %></td>
          <td><%= track.artist %></td>
          <td><%= track.album %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <button data-js-prev>Prev</button>
  <button data-js-play>Play/pause</button>
  <button data-js-next>Next</button>
  <input type="range" min="1" max="1000" value="0" data-js-scrubber>
  <div data-js-title></div>
  <div>
    <span data-js-artist></span> —
    <span data-js-album></span>
  </div>
</div>

<h3>Playlist stats</h3>

<dl>
  <dt>Number of tracks</dt>
  <dd><%= @playlist.size %></dd>

  <dt>Average valence</dt>
  <dd><%= @playlist.avg_valence %></dd>

  <dt>Max valence</dt>
  <dd><%= @playlist.max_valence %></dd>

  <dt>Min valence</dt>
  <dd><%= @playlist.min_valence %></dd>

  <dt>Valence distribution</dt>
  <dd><%= @playlist.valence_distribution.inspect %></dd>
</dl>

app/views/playlists/show_mine.html.erb
<%= flash_messages %>

<div class="playlist-view" data-js-playlist-view>

  <div class="playlist-view_weather-n-mood">
    <%= render 'weather', location: @location %>
    <%= render 'mood_rater', path: :mood_ratings_path, method: :post %>
  </div>

  <div class="playlist-view_toggle">
    <%= render 'toggle' %>
  </div>

  <div data-js-player="<%= @current_user.credentials["token"] %>">

    <script src="https://sdk.scdn.co/spotify-player.js"></script>

    <div data-js-pane="playlist">
    
      <%= button_tag "Play", class: "button", data: { icon: "play", js_play_playlist: "" } %>
      <%= link_to "Refresh", playlist_refresh_path, method: :put, class: "button", data: { icon: "refresh" } %>
      <%# link_to "Export to Spotify", playlist_refresh_path, method: :put, class: "button", data: { icon: "export" } %>
      <div class="flash -error -hide" data-js-error></div>
      <%= render 'track_listing' %>

      <% if Rails.env.development? %>
        <h3>Debug info</h3>
        <dl>
          <dt>Number of tracks</dt>
          <dd><%= @playlist.size %></dd>

          <dt>Average valence</dt>
          <dd><%= @playlist.avg_valence %></dd>

          <dt>Max valence</dt>
          <dd><%= @playlist.max_valence %></dd>

          <dt>Min valence</dt>
          <dd><%= @playlist.min_valence %></dd>

          <dt>Valence distribution</dt>
          <dd><%= @playlist.valence_distribution.inspect %></dd>
        </dl>
      <% end %>

    </div>

    <div data-js-pane="charts"></div>

    <%= render 'control_bar' %>
  </div>

</div>